name: simple-workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, wordl!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo Test, and deploy your project.

      - name: Get database pass
        env:
          SUPER_SECRET: ${{ secrets.PASSWORD_DATABASE_FAKE }}
        run: echo "$SUPER_SECRET"
